source("./analysis_methods_v1.01.R")
data<-loadIllumina("GS_Report//FinalReport.txt", groupFile = "group_all_samples.txt")
generateTechQCgraph(data, arrayType="human")
generateGroupGraphs(data,"RawDataReport")
data.p<-processData(data)
generateGroupGraphs(data.p, "NormalisedDatareport")
multipleComparisons(data, arrayType="human")       
knit("GX_report_full.Rnw")
system("pdflatex GX_report_full.tex")
